
CREATE TABLE registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    designation VARCHAR(20),

    first_name VARCHAR(100) NOT NULL,

    last_name VARCHAR(100),

    date_of_birth DATE,

    gender VARCHAR(20) NOT NULL,

    phone VARCHAR(20),

    email VARCHAR(255),

    referring_doctor_id BIGINT,

    rate_list_id BIGINT,

    registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE registration_dispatch_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    registration_id BIGINT NOT NULL,

    dispatch_method VARCHAR(30) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_registration_dispatch_method_registration
        FOREIGN KEY (registration_id)
        REFERENCES registration(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_registration_dispatch_method
        UNIQUE (registration_id, dispatch_method)
);

