CREATE TABLE billing_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(40) NOT NULL UNIQUE,
    registration_id BIGINT NOT NULL REFERENCES registration(id),
    discount NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(30),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL
);

CREATE TABLE billing_invoice_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES billing_invoice(id) ON DELETE CASCADE,
    item_code VARCHAR(40) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0)
);

CREATE INDEX idx_billing_invoice_registration ON billing_invoice(registration_id);
